name: "setup-slurm-action"
description: "Setup slurm cluster on GitHub Actions using https://github.com/galaxyproject/ansible-slurm"
branding:
  icon: arrow-down-circle
  color: blue
runs:
  using: "composite"
  steps:
    # prior to slurm-setup we need the podmand-correct command
    # see https://github.com/containers/podman/issues/13338
    - name: Download slurm ansible roles
      shell: bash -e {0}
      # ansible-galaxy role install https://github.com/galaxyproject/ansible-slurm/archive/1.0.1.tar.gz
      run: |
        ansible-galaxy role install https://github.com/mila-iqia/ansible-slurm/archive/1.1.2.tar.gz

    - name: Apt prerequisites
      shell: bash -e {0}
      run: |
        sudo apt-get update
        sudo apt-get install retry

    - name: Set XDG_RUNTIME_DIR
      shell: bash -e {0}
      run: |
        mkdir -p /tmp/1002-runtime # work around podman issue (https://github.com/containers/podman/issues/13338)
        echo XDG_RUNTIME_DIR=/tmp/1002-runtime >> $GITHUB_ENV

    - name: Setup slurm
      shell: bash -e {0}
      run: |
        ansible-playbook ./.github/custom_setup_slurm_action/slurm-playbook.yml || (journalctl -xe && exit 1)

    - name: Add Slurm Account
      shell: bash -e {0}
      run: |
        sudo retry --until=success -- sacctmgr -i create account "Name=runner"
        sudo sacctmgr -i create user "Name=runner" "Account=runner"

    - name: Test srun submission
      shell: bash -e {0}
      run: |
        srun -vvvv echo "hello world"
        sudo cat /var/log/slurm/slurmd.log

    - name: Show partition info
      shell: bash -e {0}
      run: |
        scontrol show partition

    - name: Test sbatch submission
      shell: bash -e {0}
      run: |
        sbatch -vvvv -N 1 --mem 5 --wrap "echo 'hello world'"
